# Generated by Django 5.1.7 on 2025-07-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lastprice',
            field=models.IntegerField(default=0),
        ),
    ]
