# Generated by Django 5.1.7 on 2025-07-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_menu_category_remove_menu_lastprice_menu_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_category',
            name='description',
        ),
        migrations.AlterField(
            model_name='menu',
            name='category_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='demoapp.menu_category'),
        ),
    ]
